### ISSUE TITLE
In ubuntu 16.04 libolm-dev is not present

### ISSUE THREAD

**Issue by delijati** [quotient-im/libQuotient#353]
In ubuntu 16.04 libolm-dev is not present; add it a third party also to the repo !?
```
libQuotient/3rdparty/libQtOlm/lib/account.h:4:21: fatal error: olm/olm.h: No such file or directory
```

**Comment by KitsuneRal** [comment]
There's been a complaint in another place that building Quaternion along with its dependencies is more difficult than it could be. The current QtOlm actually depends on libolm 3 which is not available even in disco; so the way forward would be to enable building olm together with QtOlm. Since this is actually a problem of QtOlm rather than libQuotient (libQuotient doesn't directly depend on libolm), I'm closing this issue and ask you to open a new one at https://gitlab.com/b0/libqtolm.
