### ISSUE TITLE
Sdk has no API documentation

### ISSUE THREAD

**Issue by code-mm** [quotient-im/libQuotient#360]

**Comment by KitsuneRal** [comment]
Thanks for making a record for this. I'd be happy to see more details on what you expect to find for documentation. I'm not saying the issue is incorrect (it very much _is_ correct) but I'd like to have at least some general requirements specified.

As for now, doc-comments are there (so if you load libQuotient in any modern IDE it should at least show you documentation on particular classes/methods). What I see missing is:
- High level design (tracked in #357) that would describe how the library is generally organised and how to use it;
- Standalone documentation (most likely generated) that could be consumed outside of an IDE.

Anything else?

**Comment by ognarb** [comment]
An online documentation could be helpful, if there is interest I could setup a version of api.kde.org without KDE branding for libQuotient. I'm quite familiar with it (maintainer of it) and it is a lot better than the default Doxygen theme.

**Comment by KitsuneRal** [comment]
Wow, yes, please!

**Comment by KitsuneRal** [comment]
Thanks to @CarlSchwan and @TobiasFella, online documentation is being served at https://quotient-im.github.io/libQuotient/ since 0.7.x times. The high-level design is tracked elsewhere (see above).
