### ISSUE TITLE
Notifications save timestamp as int

### ISSUE THREAD

**Issue by TobiasFella** [quotient-im/libQuotient#438]
In https://github.com/quotient-im/libQuotient/blob/23f2bb6ca3c0c44fd8972902b4d9b5d6c23d52e7/lib/csapi/notifications.h#L38
the timestamp is saved as int, which typically means 4 bytes, which is not enough to hold any recent timestamp

**Comment by KitsuneRal** [comment]
Caused by https://github.com/matrix-org/matrix-doc/issues/2955.

**Comment by turt2live** [comment]
*https://github.com/matrix-org/matrix-doc/issues/2954

**Comment by KitsuneRal** [comment]
With respect to things listed in my matrix-doc issue, this is fixed by 0d43150 (`notifications.h`) using the soft fork of matrix-doc; and the `ReceiptEvent` code uses manual conversion to `QDateTime` via `qint64` made back in 2019. The spec still needs to be updated but that's tracked by its own issue.
