### ISSUE TITLE
Accounts with user ids containing forward slashes can't be loaded correctly

### ISSUE THREAD

**Issue by TobiasFella** [quotient-im/libQuotient#842]
Reported as https://bugs.kde.org/show_bug.cgi?id=491252

The user id is used as a key for QSettings, which uses forward slashes as separators. When listing the account, wrong groups are thus returned.

We need to somehow come up with a way of escaping forward slashes while not breaking existing logged-in accounts (at least those that do not contain forward slashes; for the other ones, logging in again is probably inevitable but also not problematic. I haven't been able to come up with a nice way to do that yet.

**Comment by KitsuneRal** [comment]
I was about to say that forward slashes in user ids are a deprecated legacy but [no](https://spec.matrix.org/v1.12/appendices/#user-identifiers) ;(
Why can't we "simply" percent-encode the forward slashes though?

**Comment by KitsuneRal** [comment]
Okay, I think I understand at least a part of the challenge - there's plenty of places where they key is joined with the group name and `Settings` already gets the full key name, with "right" and "wrong" slashes indistinguishable from each other. Otherwise, percent-encoded slashes are double-percent-encoded by `QSettings` in the actually stored keys (if I encode `/` to `%2F` what actually gets written is `%252F`) but that's not a big deal as long as it's consistently used to match/store/remove keys I think?

**Comment by KitsuneRal** [comment]
A bigger problem is with `SettingsGroup`, specifically `childGroups()` and `remove()`, used in both Quaternion and NeoChat to respectively collect and remove accounts from the settings. The problem is that not all `SettingsGroup`s are groups of accounts and we might not want to aggressively unescape keys from any group. This can be worked around for now by checking directly whether a given group is named `Accounts`; and for 0.10 we can make a dedicated API for the accounts group, and even warn in the logs at runtime if someone tries to use `SettingsGroup(u"Accounts"_s)`.

**Comment by daandemeyer** [comment]
@KitsuneRal Thank you for fixing this! Eagerly waiting for a release with this fix so I can try out neochat again

**Comment by KitsuneRal** [comment]
It's already released, 0.9.2 has this fix.
